version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/main/frontend/package.json" }}
            - v1-dependencies-
      - run:
          name: buildSnapshottishDependencies
          command: |
            cd /tmp
            for proj in common wire actors cluster symbio symbio-jdbc lattice http; do
            git clone https://github.com/vlingo/vlingo-$proj.git
            cd vlingo-$proj
            mvn -DskipTests install
            cd ..
            done
      - run: mvn -B clean package -Pfrontend
      - persist_to_workspace:
          root: ~/project
          paths:
            - target/
            - src/main/frontend/
            - src/test/e2e/
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - target/node
            - src/main/frontend/node_modules
          key: v1-dependencies-{{ checksum "src/main/frontend/package.json" }}
  e2e-test:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          java -jar ~/project/target/vlingo-schemata-*-jar-with-dependencies.jar dev &
          export CYPRESS_BASE_URL=http://localhost:9019/app
          cd ~/project/src/test/e2e
          npm install
          npm run test-multiple
      - store_test_results:
          path: src/test/e2e/multiple-results
      - store_artifacts:
          path: src/test/e2e/cypress/videos
          destination: videos
      - store_artifacts:
          path: src/test/e2e/cypress/screenshots
          destination: screenshots
  image:
    docker:
      - image:  circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker build . -t vlingo/vlingo-schemata
      - run: |
          echo "$DOCKER_TOKEN" | docker login --username $DOCKER_USER --password-stdin
          docker push vlingo/vlingo-schemata
workflows:
  version: 2
  default-workflow:
    jobs:
      - build
      - e2e-test:
          requires:
            - build
      - image:
          requires:
            - e2e-test
          filters:
            branches:
              only:
                - master


