version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "src/main/frontend/package.json" }}
            - v2-dependencies-
      - run:
          name: buildSnapshottishDependencies
          command: |
            cd /tmp
            for proj in common wire actors cluster symbio symbio-jdbc lattice http; do
            git clone https://github.com/vlingo/vlingo-$proj.git
            cd vlingo-$proj
            mvn -DskipTests install
            cd ..
            done
      - run: mvn -B clean package -Pfrontend
      - persist_to_workspace:
          root: ~/project
          paths:
            - Dockerfile
            - target/
            - src/main/frontend/
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - target/node
            - src/main/frontend/node_modules
          key: v2-dependencies-{{ checksum "src/main/frontend/package.json" }}
  image:
    docker:
      - image:  circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker build . -t vlingo/vlingo-schemata
      - run: |
          echo "$DOCKER_TOKEN" | docker login --username $DOCKER_USER --password-stdin
          docker push vlingo/vlingo-schemata
workflows:
  version: 2
  default-workflow:
    jobs:
      - build
      - image:
          requires:
            - build
          filters:
            branches:
              only:
                - master


